// import { AiFillpcs } from "react-icons/ai";

const data = [
  {
    img: "https://5.imimg.com/data5/SELLER/Default/2022/7/MU/PJ/SD/5742893/maggi-noodles.jpg",
    title: "MASALA MAGGGI",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },
  {
    img: "https://5.imimg.com/data5/SELLER/Default/2022/7/MU/PJ/SD/5742893/maggi-noodles.jpg",
    title: "MASALA MAGGGI",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },
  {
    img: "https://5.imimg.com/data5/SELLER/Default/2022/7/MU/PJ/SD/5742893/maggi-noodles.jpg",
    title: "MASALA MAGGGI",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },
  {
    img: "https://5.imimg.com/data5/SELLER/Default/2022/7/MU/PJ/SD/5742893/maggi-noodles.jpg",
    title: "MASALA MAGGGI",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDB2jyf_TsXM7ZAoVLq2uMvrv1AjTqMHVFxQ&usqp=CAU",
    title: "AAM PAPAD",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDB2jyf_TsXM7ZAoVLq2uMvrv1AjTqMHVFxQ&usqp=CAU",
    title: "AAM PAPAD",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDB2jyf_TsXM7ZAoVLq2uMvrv1AjTqMHVFxQ&usqp=CAU",
    title: "AAM PAPAD",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDB2jyf_TsXM7ZAoVLq2uMvrv1AjTqMHVFxQ&usqp=CAU",
    title: "AAM PAPAD",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDB2jyf_TsXM7ZAoVLq2uMvrv1AjTqMHVFxQ&usqp=CAU",
    title: "AAM PAPAD",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },

  {
    img: "./sample.png",
    title: "AASHIRWAD ATTA",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },
  {
    img: "./sample.png",
    title: "AASHIRWAD ATTA",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },
  {
    img: "./sample.png",
    title: "AASHIRWAD ATTA",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },
  {
    img: "./sample.png",
    title: "AASHIRWAD ATTA",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },
  {
    img: "./sample.png",
    title: "AASHIRWAD ATTA",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },
  {
    img: "https://rukminim2.flixcart.com/image/850/1000/xif0q/edible-oil/3/w/l/-original-imagspghd9dzyj4r.jpeg?q=90",
    title: "FORTUNE SOYA OIL",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },
  ,
  {
    img: "./sample.png",
    title: "AASHIRWAD ATTA",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },
  {
    img: "https://rukminim2.flixcart.com/image/850/1000/xif0q/edible-oil/3/w/l/-original-imagspghd9dzyj4r.jpeg?q=90",
    title: "FORTUNE SOYA OIL",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },
  {
    img: "./sample.png",
    title: "AASHIRWAD ATTA",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },
  {
    img: "https://rukminim2.flixcart.com/image/850/1000/xif0q/edible-oil/3/w/l/-original-imagspghd9dzyj4r.jpeg?q=90",
    title: "FORTUNE SOYA OIL",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },
  {
    img: "https://rukminim2.flixcart.com/image/850/1000/xif0q/edible-oil/3/w/l/-original-imagspghd9dzyj4r.jpeg?q=90",
    title: "FORTUNE SOYA OIL",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },
  {
    img: "https://rukminim2.flixcart.com/image/850/1000/xif0q/edible-oil/3/w/l/-original-imagspghd9dzyj4r.jpeg?q=90",
    title: "FORTUNE SOYA OIL",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },
  {
    img: "./sample.png",
    title: "AASHIRWAD ATTA",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0_4RVRJL-tsZ6QDnnJwjWLQROre3oLMDC8KJZGFgAMptoZ-bgWyGpDH_Cy2Ml08udof0&usqp=CAU",
    title: "LAYS CHIPS",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0_4RVRJL-tsZ6QDnnJwjWLQROre3oLMDC8KJZGFgAMptoZ-bgWyGpDH_Cy2Ml08udof0&usqp=CAU",
    title: "LAYS CHIPS",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0_4RVRJL-tsZ6QDnnJwjWLQROre3oLMDC8KJZGFgAMptoZ-bgWyGpDH_Cy2Ml08udof0&usqp=CAU",
    title: "LAYS CHIPS",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },

  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0_4RVRJL-tsZ6QDnnJwjWLQROre3oLMDC8KJZGFgAMptoZ-bgWyGpDH_Cy2Ml08udof0&usqp=CAU",
    title: "LAYS CHIPS",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0_4RVRJL-tsZ6QDnnJwjWLQROre3oLMDC8KJZGFgAMptoZ-bgWyGpDH_Cy2Ml08udof0&usqp=CAU",
    title: "LAYS CHIPS",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },
  {
    img: "./sample.png",
    title: "AASHIRWAD ATTA",
    pcs: "644 PCS",
    cases: "CASE(50X250 Gram)",
    prevPrice: "₹200",
    newPrice: "₹150",
    // company: "Nike",
    // color: "white",
    // category: "sneakers",
  },
];

export default data;
